"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

NAME = 'HelloPyObjC'
APP = ['main.py']
DATA_FILES = []
#DATA_FILES = ['MainMenu.xib']
OPTIONS = {
    'packages': ['objc']
}

setup(
      name=NAME,
      app=APP,
      data_files=DATA_FILES,
      options={'py2app': OPTIONS},
      setup_requires=['py2app'],
)
